import * as THREE from 'three';
import { GLTFLoader, type GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import { clone } from 'three/examples/jsm/utils/SkeletonUtils.js';

export const weaponModels:Record<string,string>={vxr:'AR_1',kestrel:'SMG_1',obelisk:'Sniper_1',breach:'Shotgun_1',atlas:'AR_4',arc:'AR_3',sidearm:'Pistol_1',tactical:'AR_2',heavy:'Grenade_1'};
export { default as assetNames } from './asset-catalog.json';
import assetNames from './asset-catalog.json';
export class AssetLibrary {
 models=new Map<string,GLTF>();
 dispose(){const textures=new Set<THREE.Texture>();for(const gltf of this.models.values())gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material]){for(const v of Object.values(m))if(v instanceof THREE.Texture)textures.add(v);m.dispose();}}});textures.forEach(t=>t.dispose());this.models.clear();}
 async load(progress:(n:number)=>void){const loader=new GLTFLoader();let done=0;await Promise.all(assetNames.map(async name=>{const gltf=await loader.loadAsync(`./assets/${name}.glb`);this.models.set(name,gltf);progress(++done/assetNames.length);}));return this;}
 surface(name:string,width:number,depth:number,repeat:number){const gltf=this.models.get(name)!;let original:THREE.MeshStandardMaterial|undefined;gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh&&!original)original=(Array.isArray(o.material)?o.material[0]:o.material) as THREE.MeshStandardMaterial;});const material=original!.clone();for(const key of ['map','normalMap','roughnessMap'] as const){const texture=material[key];if(texture){material[key]=texture.clone();material[key]!.wrapS=material[key]!.wrapT=THREE.RepeatWrapping;material[key]!.repeat.set(repeat,repeat);}}material.side=THREE.DoubleSide;const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,depth),material);mesh.rotation.x=-Math.PI/2;mesh.receiveShadow=true;mesh.name=name;return mesh;}
 model(name:string,height:number){const source=this.models.get(name);if(!source)throw new Error(`Missing asset: ${name}`);const object=clone(source.scene);object.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(object);const size=box.getSize(new THREE.Vector3());const s=height/Math.max(size.y,.001);object.scale.multiplyScalar(s);object.position.set(-(box.min.x+box.max.x)*s/2,-box.min.y*s,-(box.min.z+box.max.z)*s/2);const root=new THREE.Group();root.name=name;root.userData.asset=name;root.add(object);root.traverse(o=>{if(o instanceof THREE.Mesh){o.castShadow=true;o.receiveShadow=true;o.geometry=o.geometry.clone();o.material=Array.isArray(o.material)?o.material.map(m=>m.clone()):o.material.clone();}});if(Object.values(weaponModels).includes(name))root.traverse(o=>{if(o instanceof THREE.Mesh){const ms=Array.isArray(o.material)?o.material:[o.material];for(const material of ms){const m=material as THREE.MeshStandardMaterial;if(m.name==='Main')m.color.set(0x344447);if(m.name==='White')m.color.set(0x687377);m.roughness=.55;}}});if(name.includes('Story'))root.traverse(o=>{if(o instanceof THREE.Mesh){const m=o.material as THREE.MeshStandardMaterial;if(m.name==='Glass'){m.color.set(0x165f70);m.emissive.set(0x32c9e0);m.emissiveIntensity=1.1;}if(['Main','Bricks'].includes(m.name)){m.color.set(0x374654);m.roughness=.8;}if(m.name==='White')m.color.set(0x697b83);}});return root;}
 arms(){const root=this.actor('Infantry');root.traverse(o=>{if(!(o instanceof THREE.Mesh))return;if(!(o instanceof THREE.SkinnedMesh)){o.visible=false;return;}const g=o.geometry,si=g.getAttribute('skinIndex'),sw=g.getAttribute('skinWeight');const armBones=new Set(o.skeleton.bones.map((b,i)=>(/^(hand|finger|thumb)/i.test(b.name)&&!/armor/i.test(b.name))?i:-1));const keep=(v:number)=>{let weight=0;for(let k=0;k<4;k++)if(armBones.has(si.getComponent(v,k)))weight+=sw.getComponent(v,k);return weight>.6;};const old=g.index;const indices:number[]=[];const count=old?.count||g.getAttribute('position').count;for(let i=0;i<count;i+=3){const a=old?old.getX(i):i,b=old?old.getX(i+1):i+1,c=old?old.getX(i+2):i+2;if(keep(a)&&keep(b)&&keep(c))indices.push(a,b,c);}g.setIndex(indices);g.clearGroups();o.visible=indices.length>0;o.frustumCulled=false;});animateActor(root,'idle',.01);return root;}
 actor(name:string,height=1.85){const root=this.model(name,height);if(name==='Infantry')root.rotation.y=-Math.PI/2;const mixer=new THREE.AnimationMixer(root);const actions:Record<string,THREE.AnimationAction>={};for(const clip of this.models.get(name)!.animations)actions[clip.name.split('|').pop()!]=mixer.clipAction(clip);root.userData.animator={mixer,actions,current:''};return root;}
}
export function animateActor(root:THREE.Object3D,state:string,dt:number){const a=root.userData.animator;if(!a)return;const aliases:Record<string,string[]>={idle:['Idle_Gun_Pointing','Idle'],walk:['Walk'],run:['Run'],fire:['Shoot','Run_Shoot'],death:['Death','Dead'],hit:['HitRecieve'],melee:['Punch_Right','Attack'],interact:['Interact'],crouch:['Crouch'],crouchWalk:['CrouchWalk'],jump:['Jump'],land:['Land'],raise:['Raise'],lower:['Lower']};const key=(aliases[state]||[state]).find(k=>a.actions[k]);if(key&&key!==a.current){const next=a.actions[key] as THREE.AnimationAction;next.reset();if(['death','jump','land','raise','lower'].includes(state)){next.setLoop(THREE.LoopOnce,1);next.clampWhenFinished=true;}next.play();if(a.current)next.crossFadeFrom(a.actions[a.current],.18,true);a.current=key;}a.mixer.update(dt);}

/** Bake static imported meshes by material, retaining authored geometry and normals. */
export function batchStatic(scene:THREE.Scene,roots:THREE.Group[]){
 const buckets=new Map<string,{material:THREE.Material;geometries:THREE.BufferGeometry[]}>();
 for(const root of roots){root.updateMatrixWorld(true);root.traverse(o=>{if(!(o instanceof THREE.Mesh)||Array.isArray(o.material))return;const m=o.material as THREE.MeshStandardMaterial;const key=[m.color?.getHex(),m.emissive?.getHex(),m.emissiveIntensity,m.roughness,m.metalness,m.map?.uuid,m.normalMap?.uuid,m.roughnessMap?.uuid,m.metalnessMap?.uuid,m.alphaTest,m.transparent,m.side].join('/');let bucket=buckets.get(key);if(!bucket){bucket={material:m.clone(),geometries:[]};buckets.set(key,bucket);}const g=(o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone());for(const name of Object.keys(g.attributes))if(!['position','normal','uv'].includes(name))g.deleteAttribute(name);if(!g.getAttribute('uv'))g.setAttribute('uv',new THREE.BufferAttribute(new Float32Array(g.getAttribute('position').count*2),2));g.applyMatrix4(o.matrixWorld);bucket.geometries.push(g);});scene.remove(root);}
 for(const {material,geometries} of buckets.values()){const geometry=mergeGeometries(geometries);if(geometry){const mesh=new THREE.Mesh(geometry,material);mesh.name='Batched imported architecture';mesh.castShadow=true;mesh.receiveShadow=true;scene.add(mesh);}geometries.forEach(g=>g.dispose());}
 for(const root of roots)root.traverse(o=>{if(o instanceof THREE.Mesh){o.geometry.dispose();if(!Array.isArray(o.material))o.material.dispose();}});
}
